apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    app: nginx-app-cutom
spec:
  containers:
  - name: nginx-app-container
    image: poojasdocker2023/nginx-app-cutom:latest
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-app-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-app-cutom
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80